In [7]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

[162, 163, 165, 8364, 164]

In [8]:
beyond_ascii = list(filter(lambda c : c > 127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

In [14]:
colors = ['black', 'white']
sizes = ['S','M','L']
tshirts = [[color, size] for color in colors for size in sizes]
tshirts

[['black', 'S'],
 ['black', 'M'],
 ['black', 'L'],
 ['white', 'S'],
 ['white', 'M'],
 ['white', 'L']]

In [10]:
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [12]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [13]:
colors = ['black', 'white']
sizes = ['S','M','L']
for tshirt in ('%s %s' %(c,s) for c in colors for s in sizes):
    print(tshirt) 

black S
black M
black L
white S
white M
white L


In [21]:
number_list = [1, 2, 5]
a, b, c = number_list
print(f"a : {a}, b : {b}, c : {c}")

a : 1, b : 2, c : 5


In [22]:
c, a, b = a, b, c
print(f"a : {a}, b : {b}, c : {c}")

a : 2, b : 5, c : 1


In [1]:
t = (20,8)
divmod(t)

TypeError: divmod expected 2 arguments, got 1

In [2]:
divmod(*t)

(2, 4)

In [3]:
travler_ids = [('USA','31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for country, _ in travler_ids:
    print(country)
_

USA
BRA
ESP


'XDA205856'

In [5]:
from collections import namedtuple
City = namedtuple('City', 'name coutnry population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
print(tokyo)
print(tokyo.coordinates)

City(name='Tokyo', coutnry='JP', population=36.933, coordinates=(35.689722, 139.691667))
(35.689722, 139.691667)


In [6]:
City._fields

('name', 'coutnry', 'population', 'coordinates')

In [7]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613899, 77.208889))
delhi = City._make(delhi_data)
delhi

City(name='Delhi NCR', coutnry='IN', population=21.935, coordinates=LatLong(lat=28.613899, long=77.208889))

In [8]:
delhi._asdict()

{'name': 'Delhi NCR',
 'coutnry': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613899, long=77.208889)}

In [11]:
for key, value in delhi._asdict().items():
    print(key, value)

name Delhi NCR
coutnry IN
population 21.935
coordinates LatLong(lat=28.613899, long=77.208889)


In [2]:
tu = (1,2,3)
tu.__contains__(2)

True

In [13]:
tu.__iter__()

In [8]:
tu.__len__()

3

In [9]:
tu.__mul__(2)

(1, 2, 3, 1, 2, 3)

In [18]:
invoice = """
0.....6.................................40........52...55........
1909 Pimoroni PiBrella                      $17.50    3    $52.50
1489 6mm Tactile Switch x20                  $4.95    2    $9.90
1510 Panavise Jr. - PV-201                  $28.00    1    $28.00
1601 PiTFT Mini Kit 320x240                 $34.95    1    $34.95
"""

SKU = slice(0, 6)
DESCRIPTION = slice(5, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION], item[QUANTITY])

    $17.50   Pimoroni PiBrella                     3
     $4.95   6mm Tactile Switch x20                2
    $28.00   Panavise Jr. - PV-201                 1
    $34.95   PiTFT Mini Kit 320x240                1
  


In [21]:
l = list(range(10))
l[2:5] = 100
l

TypeError: can only assign an iterable

In [22]:
t = (1,2, [30,40])
t[2] += [50,60]

TypeError: 'tuple' object does not support item assignment

In [23]:
t

(1, 2, [30, 40, 50, 60])

In [24]:
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


In [25]:
intlist = [5,1,2,3]
print(id(intlist),id(intlist.sort()), id(sorted(intlist)))

1406483111104 140722502998144 1406481826176


In [26]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted(fruits))
print(fruits)
print(sorted(fruits, reverse=True))
print(sorted(fruits, key=len))
print(sorted(fruits, key=len, reverse=True))
print(fruits)
print(fruits.sort())
print(fruits)

['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']
['raspberry', 'banana', 'grape', 'apple']
['grape', 'raspberry', 'apple', 'banana']
None
['apple', 'banana', 'grape', 'raspberry']


In [5]:
"""
bisect_demo.py
Demonstration of ``bisect.bisect``::
    >>> import bisect
    >>> demo(bisect.bisect)
    31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
    30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
    29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
    23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
    22 @  9      |  |  |  |  |  |  |  |  |22
    10 @  5      |  |  |  |  |10
     8 @  5      |  |  |  |  |8
     5 @  3      |  |  |5
     2 @  1      |2
     1 @  1      |1
     0 @  0    0
Demonstration of ``bisect.bisect_left``::
    >>> demo(bisect.bisect_left)
    31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
    30 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |30
    29 @ 12      |  |  |  |  |  |  |  |  |  |  |  |29
    23 @  9      |  |  |  |  |  |  |  |  |23
    22 @  9      |  |  |  |  |  |  |  |  |22
    10 @  5      |  |  |  |  |10
     8 @  4      |  |  |  |8
     5 @  2      |  |5
     2 @  1      |2
     1 @  0    1
     0 @  0    0
"""

# tag::BISECT_DEMO[]
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)  # <1>
        offset = position * '  |'  # <2>
        print(ROW_FMT.format(needle, position, offset))  # <3>

if __name__ == '__main__':

    if sys.argv[-1] == 'left':    # <4>
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('DEMO:', bisect_fn.__name__)  # <5>
    print('haystack ->', ' '.join(f'{n:2}' for n in HAYSTACK))
    demo(bisect_fn)

# end::BISECT_DEMO[]

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [4]:
sys.argv[-1]

'--f=c:\\Users\\kland\\AppData\\Roaming\\jupyter\\runtime\\kernel-v2-8468jEhqbIquGZK1.json'

In [6]:
import bisect
result = []
scores = [33, 99, 77, 70, 89, 90, 100] # 애들이 받은 점수
grades = [60, 70, 80, 90] # 기준점수를 등급으로 바꿔주자
for score in scores:
    pos = bisect.bisect(grades, score)  
    # 학생들의 점수를 grades = 기준에 넣는다고 가정했을때 어디 들어가면 될까
    grade = 'FDCBA'[pos] # bisect는 인덱스만 리턴한다.
    result.append(grade)

print(result)

['F', 'A', 'C', 'C', 'B', 'A', 'A']


In [7]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE * 2)
    bisect.insort(my_list, new_item)
    print(f'{new_item:2d} -> {my_list}')

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [11]:
from array import array
array('d', [1.0, 2.0, 3.14])

array('d', [1.0, 2.0, 3.14])

In [30]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [31]:
list(memv)

[-2, -1, 0, 1, 2]

In [32]:
memv[0]

-2

In [33]:
memv_oct = memv.cast('B')   #타입코드 B는 unsigned int 이기에 1024
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [34]:
memv_oct[5] = 4

In [35]:
numbers

array('h', [-2, -1, 1024, 1, 2])

In [36]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
type(a)

numpy.ndarray

In [38]:
a.shape

(12,)

In [40]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a[2], a[2,1], a[:1]

(array([ 8,  9, 10, 11]), 9, array([[0, 1, 2, 3]]))

In [42]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [49]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
dq.appendleft(1)

In [51]:
dq

deque([1, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
dq.rotate(3)
dq

deque([6, 7, 8, 1, 0, 1, 2, 3, 4, 5])

In [53]:
dq.rotate(-4)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 1])

In [54]:
dq.appendleft([1,2,3])

In [55]:
dq

deque([[1, 2, 3], 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
dq.extendleft([1,2,3])

In [57]:
dq

deque([3, 2, 1, [1, 2, 3], 0, 1, 2, 3, 4, 5])